version: '3.8'

services:
  nid-extraction-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nid-extraction-api
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=NID Information Extraction API
      - DEBUG=False
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
      - ENABLE_CACHE=True
      - RATE_LIMIT_ENABLED=True
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nid-network

networks:
  nid-network:
    driver: bridge
